// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPAtxNDkcHinYE4y9P2hb60eWKrf6yGf0',
    appId: '1:143344970664:web:053c73ffd8213265b20b9d',
    messagingSenderId: '143344970664',
    projectId: 'ecommerce-flutter-a437c',
    authDomain: 'ecommerce-flutter-a437c.firebaseapp.com',
    storageBucket: 'ecommerce-flutter-a437c.firebasestorage.app',
    measurementId: 'G-PGYYJC4TD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoCZ_SaXH6BJ9LawA8w1AyPCt_5aWqoHU',
    appId: '1:143344970664:android:6e5be10aba23bf8eb20b9d',
    messagingSenderId: '143344970664',
    projectId: 'ecommerce-flutter-a437c',
    storageBucket: 'ecommerce-flutter-a437c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPAtxNDkcHinYE4y9P2hb60eWKrf6yGf0',
    appId: '1:143344970664:web:7c328b055e47bf1ab20b9d',
    messagingSenderId: '143344970664',
    projectId: 'ecommerce-flutter-a437c',
    authDomain: 'ecommerce-flutter-a437c.firebaseapp.com',
    storageBucket: 'ecommerce-flutter-a437c.firebasestorage.app',
    measurementId: 'G-ESVLF1FLKH',
  );
}
